---
title: "Cell Mixture Experiment using 10X Genomics Sequencing"
author: |
  Martin Grasshoff<sup>1</sup>, Ivan G. Costa<sup>1</sup>

affiliations: |
  1. Institute for Computational Genomics, Faculty of Medicine, RWTH Aachen University, Aachen, 52074 Germany

output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{10x CellMixture SIGURD}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
header-includes:
  - \usepackage[utf8]{inputenc}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Cell Mixture Experiment using 10X Genomics Sequencing

Here, we reproduce the analysis of a cell mixture experiment. 

## Loading necessary packages.

We load the data from MAESTER. 

```{r Packages}
print("Libraries for SIGURD.")
suppressPackageStartupMessages(library(sigurd))
suppressPackageStartupMessages(library(SummarizedExperiment))
suppressPackageStartupMessages(library(ggplot2))
```

## We load the Seurat object for the scRNA-seq data.

```{r warning = FALSE}
seu <- readRDS(system.file("extdata", "data/TenX_CellLineMix_Seurat_Keep_Renamed.rds", package = "sigurd"))
```

## Loading the data using SIGURD.

```{r warning = FALSE}
# The design matrix contains information for the genotyping data.
genotyping <- LoadingMAEGATK_typewise(patient = "TenX", samples_file = "data/MAESTER_Reproduction.csv", min_cells = 0, type_use = "Amplicon_MT", verbose = FALSE)

# Removing cells that are not in the Seurat object.
genotyping <- Filtering(genotyping, cells_include = colnames(seu))

# Adding meta data do the SIGURD object.
colData(genotyping)$CellType <- seu$CellType
```

## Selecting the Variants of Interest

```{r warning = FALSE}
# Selecting informative variants. 
voi.ch.sigurd <- VariantSelection_Quantile(genotyping, min_coverage = 20, min_quality = 30, quantiles = c(0.1, 0.9), thresholds = c(0.1, 0.9), verbose = FALSE)
print(voi.ch.sigurd)
```

## Visualisation using SIGURD

```{r warning = FALSE, fig.width = 6, fig.height = 4, dev = "CairoPNG"}
# Determining if a cell is supporting one of the two cell types.
cell_support <- CallSupport(SE = genotyping, VOI_group1 = voi.ch.sigurd[voi.ch.sigurd != "chrM_7990_C_T"], VOI_group2 = "chrM_7990_C_T", group1_name = "K562", group2_name = "BT142", min_mutated_reads = 3, min_reads = 30, group_factor = c(10,2), verbose = FALSE)
cell_support_nosupport <- CallSupport(SE = genotyping, VOI_group1 = voi.ch.sigurd[voi.ch.sigurd != "chrM_7990_C_T"], VOI_group2 = "chrM_7990_C_T", group1_name = "K562", group2_name = "BT142", min_mutated_reads = 3, min_reads = 30, group_factor = c(10,2), verbose = FALSE, return_nonsupport = FALSE)
genotyping <- Filtering(genotyping, cells_include = cell_support_nosupport$Cell, verbose = FALSE)
colData(genotyping)$CellTyype_MT <- cell_support_nosupport$Support

# Plotting the results on a heatmap.
HeatmapVoi(SE = genotyping, voi = voi.ch.sigurd, annotation_trait = "CellType", minimum_coverage = 3)

voi.ch.lineages <- sigurd::VariantSelection_Group(SE = genotyping, min_coverage = 100, quantiles = c(0.01, 0.99), thresholds = c(0.01, 0.02), min_quality = 30,
                                                  group_of_interest = "CellType_MT", group1 = "K562", group2 = "BT142", group_factor = 5, remove_nocall = FALSE, verbose = FALSE)
voi.ch.lineages <- voi.ch.lineages[!voi.ch.lineages %in% blocklist.var.sigurd]
```
