#'We load the matrix generated by LoadingVarTrix.R and filter the cells and genes.
#'We do this for one sample at a time.
#'We want to remove:
#'- all cells that are blacklisted,
#'- all cells that are not in the Seurat object,
#'- all cells that do not have at least one variant with >1 (Reference),
#'- all variants that are for alternative transcripts,
#'- all variants that are always NoCall.
#'@import fastmatch Matrix Seurat SummarizedExperiment
#'@param se SummarizedExperiment object.
#'@param patient Patient you are analysing. Character.
#'@param blacklisted_barcodes_path Barcodes you want to remove. Path to a file with one column without header.
#'@param fraction_threshold Variants with an VAF below this threshold are set to 0. Numeric.
#'@param path_seurat Path to a Seurat object.
#'@export
Filtering <- function(se, patient, blacklisted_barcodes_path = "NULL", fraction_threshold = 0.5, path_seurat = "NULL"){
  print("We remove all blacklisted bar codes.")
  if(blacklisted_barcodes_path != "NULL"){
    print("We remove the unwanted cell barcodes.")
    blacklisted_barcodes <- read.table(blacklisted_barcodes_path, header = FALSE)
    blacklisted_barcodes <- blacklisted_barcodes[,1]
    barcodes_keep <- colnames(se)
    barcodes_keep <- barcodes_keep[!barcodes_keep %in% blacklisted_barcodes]
    se <- se[, barcodes_keep]
  }

  if(path_seurat != "NULL"){
    print("We load the Seurat object.")
    scrna <- load_object(path_seurat)

    print("We remove all cells that are not in the Seurat object.")
    seu_cells <- colnames(se)
    seu_cells <- seu_cells[seu_cells %in% colnames(scrna)]
    se <- se[,seu_cells]
  }

  print("We remove all variants for alternative transcripts.")
  keep_variants <- !grepl("_ENST", rownames(se))
  se <- se[keep_variants,]


  print("We assume that cells with a fraction smaller than our threshold are actually reference.")
  print("We set consensus values to 1 (Ref) and fraction values to 0.")
  print(paste0("We do not set fractions between ", fraction_threshold, " and 1 to 1."))
  print("This way, we retain the heterozygous information.")
  assays(se)$consensus[assays(se)$fraction > 0 & assays(se)$fraction < fraction_threshold] <- 1
  assays(se)$fraction[assays(se)$fraction > 0 & assays(se)$fraction < fraction_threshold] <- 0


  print("We remove all the variants that are always NoCall.")
  consensus_test <- assays(se)$consensus > 0
  keep_variants <- rowSums(consensus_test) > 0
  se <- se[keep_variants,]

  print("We remove variants, that are not at least detected in 2 cells.")
  keep_variants <- rowSums(assays(se)$consensus >= 2)
  keep_variants <- keep_variants >= 2
  se <- se[keep_variants,]


  print("We remove all cells that are not >= 1 (Ref) for at least 1 variant.")
  consensus_test <- assays(se)$consensus > 0
  keep_cells <- colSums(consensus_test) > 0
  se <- se[,keep_cells]
  return(se)
}
